import { NextResponse } from 'next/server';
import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY || 'stub_key');
const rateLimitMap = new Map<string, { count: number, resetTime: number }>();

export async function POST(request: Request) {
  try {
    // Basic IP Rate Limiting
    const ip = request.headers.get('x-forwarded-for') || 'unknown';
    const now = Date.now();
    const rateData = rateLimitMap.get(ip) || { count: 0, resetTime: now + 60000 };
    
    if (now > rateData.resetTime) {
      rateData.count = 0;
      rateData.resetTime = now + 60000;
    }
    rateData.count++;
    rateLimitMap.set(ip, rateData);

    if (rateData.count > 5) {
      return NextResponse.json({ error: 'Too many lead submissions. Please try again later.' }, { status: 429 });
    }

    const { email, businessName, deficitScore, isPartial, location, websiteUrl } = await request.json();

    if (!businessName) {
      return NextResponse.json({ error: 'Business name is required.' }, { status: 400 });
    }

    if (!isPartial) {
      if (!email) {
        return NextResponse.json({ error: 'Email is required for full lead capture.' }, { status: 400 });
      }
      // Basic server-side email format validation
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(email)) {
        return NextResponse.json({ error: 'Invalid email format provided.' }, { status: 400 });
      }
    }

    if (process.env.RESEND_API_KEY) {
      // Basic sanitization config to prevent XSS via businessName payload
      const safe = (s: string) => String(s || '').replace(/</g, '&lt;').replace(/>/g, '&gt;');
      
      const subject = isPartial 
        ? `Partial Lead (Gate Bounce Risk): ${businessName}` 
        : `New Trust Deficit Lead: ${businessName}`;

      const emailLayout = `
        <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
          <div style="background-color: ${isPartial ? '#fef3c7' : '#dcfce7'}; padding: 20px; text-align: center; border-radius: 8px 8px 0 0; border-bottom: 2px solid ${isPartial ? '#f59e0b' : '#22c55e'};">
            <h2 style="margin: 0; color: ${isPartial ? '#92400e' : '#166534'};">
              ${isPartial ? '⚠️ Partial Lead (Gate Bounce)' : '✅ Fully Converted Lead'}
            </h2>
            <p style="margin: 8px 0 0 0; font-size: 14px; opacity: 0.8;">Generated by Trust Deficit Calculator</p>
          </div>
          <div style="padding: 24px; background-color: #f9fafb; border: 1px solid #e5e7eb; border-top: none; border-radius: 0 0 8px 8px;">
            <table style="width: 100%; border-collapse: collapse;">
              <tr>
                <td style="padding: 12px 0; border-bottom: 1px solid #e5e7eb; width: 40%; color: #6b7280; font-weight: 500;">Business Name</td>
                <td style="padding: 12px 0; border-bottom: 1px solid #e5e7eb; width: 60%; font-weight: 600; color: #111827;">${safe(businessName)}</td>
              </tr>
              <tr>
                <td style="padding: 12px 0; border-bottom: 1px solid #e5e7eb; color: #6b7280; font-weight: 500;">Location</td>
                <td style="padding: 12px 0; border-bottom: 1px solid #e5e7eb; font-weight: 600; color: #111827;">${safe(location)}</td>
              </tr>
              <tr>
                <td style="padding: 12px 0; border-bottom: 1px solid #e5e7eb; color: #6b7280; font-weight: 500;">Website</td>
                <td style="padding: 12px 0; border-bottom: 1px solid #e5e7eb;">
                  ${websiteUrl ? `<a href="${safe(websiteUrl)}" style="color: #2563eb; text-decoration: none; font-weight: 600;">${safe(websiteUrl)}</a>` : '<em style="color: #9ca3af;">None Provided</em>'}
                </td>
              </tr>
              <tr>
                <td style="padding: 12px 0; ${!isPartial ? 'border-bottom: 1px solid #e5e7eb;' : ''} color: #6b7280; font-weight: 500;">Contact Email</td>
                <td style="padding: 12px 0; ${!isPartial ? 'border-bottom: 1px solid #e5e7eb;' : ''} font-weight: 600;">
                  ${!isPartial ? `<a href="mailto:${safe(email)}" style="color: #2563eb; text-decoration: none;">${safe(email)}</a>` : '<em style="color: #dc2626;">Bounced at Gate</em>'}
                </td>
              </tr>
              ${!isPartial ? `
              <tr>
                <td style="padding: 12px 0; color: #6b7280; font-weight: 500;">Deficit Score</td>
                <td style="padding: 12px 0; font-weight: bold; color: #dc2626;">${deficitScore}</td>
              </tr>
              ` : ''}
            </table>
          </div>
        </div>
      `;

      const data = await resend.emails.send({
        from: 'onboarding@resend.dev', // Use Resend's default onboarding address for testing unverified domains
        to: ['trevor@truepath406.com'],
        subject: subject,
        html: emailLayout,
      });

      console.log('✅ Lead Captured & Sent:', { businessName, email, isPartial });
      return NextResponse.json({ success: true, data });
    } else {
      console.log('🧪 TEST MODE (No API Key): Lead Data Captured:', { email, businessName, location, websiteUrl });
      return NextResponse.json({ success: true, mocked: true });
    }
  } catch (error) {
    console.error('Error sending lead email:', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}
